- name: Deploy updated version of site
  hosts: web
  user: deploy
  sudo: no
  vars: 
    go_path: /home/deploy/go
    app_dir: /home/deploy/go/src/github.com/danjac/podbaby
    repo: github.com/danjac/podbaby
  tasks:
    - include_vars: vars/env.yml

    - name: generate .env file 
      copy:
          content: "{{ env_file }}"
          dest: "{{ app_dir }}/.env"

    - name: update repo
      command: "git pull https://{{ repo }} chdir={{app_dir}}"

    - name: rebuild go app
      command: "go get -u {{ repo }}"
      environment:
          GOPATH: "{{ go_path }}"

    - name: run database migrations
      command: "migrate -path={{ app_dir }}/sql/migrations -url={{ db_url }} up"
      environment:
          PATH: "$PATH:{{ go_path }}/bin"

    - name: restart web service
      command: supervisorctl restart podbaby
      sudo: yes

