- name: Update apt packages
  hosts: web
  user: deploy
  become: yes
  become_method: sudo
  tasks:

    - name: update packages
      apt: update_cache=yes

    - name: restart web service
      command: supervisorctl restart podbaby

